/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
country, COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY country

-- Total Customers by Gender

SELECT 
gender, COUNT(*) AS total
FROM gold.dim_customers
GROUP BY gender

-- Find total products by catergory

SELECT  Category, COUNT (*) AS total_products
FROM gold.dim_product
GROUP BY Category

-- Average Costs in each Category

SELECT Category, AVG(cost) AS avg_Cost
FROM gold.dim_product
GROUP BY Category
ORDER BY avg_Cost DESC

-- Total revenue generated for each category

SELECT P.Category, SUM(S.sales_amount) AS total_sales
FROM gold.Fact_Sales S 
LEFT JOIN  gold.dim_product P ON P.product_key = S.product_key
GROUP BY Category

-- Total revenue generated by each Customer

SELECT customer_id, SUM(sales_amount) AS total_sales
FROM gold.Fact_Sales S 
LEFT JOIN  gold.dim_customers C ON C.customer_key = S.customer_key
GROUP BY customer_id

-- Distribution of sold items across Countries

SELECT country, COUNT(quantity)
FROM gold.dim_customers C
RIGHT JOIN gold.Fact_Sales S 
ON c.customer_key = S.customer_key
GROUP BY country









